### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by extracat** [daneden/Zeitgeist#100]
I guess it stoped working. Where are no projects shown in the app, after connecting vercel. It worked fine previously.

App Version: 3.1		Device: iPhone 12 Pro
		OS: iOS 17.1.1

**Comment by Jadonus** [comment]
#97 fixes this. Soon it will be pushed to the App Store.

**Comment by extracat** [comment]
I tested 3.2.1: if I connect it to vercel and select exact projects everything is fine. But if I grant access to all projects — it does not show any project.
