### ISSUE TITLE
When I was setting up the app the Safari mobile in app browser made it nearly impossible to click the right scope for my project. The iPhone keyboard would not disappear in Vercel's drop-down. Not sure if there's a way you guys can fix this since it seems to be a UX issue with Vercel but maybe tell users that the fix is zooming out really far on the browser so that it renders appropriately!

### ISSUE THREAD

**Issue by SohamGovande** [daneden/Zeitgeist#105]
> Please give a detailed description of the issue you’re experiencing or the feedback you’d like to provide.
> Feel free to attach any relevant screenshots or logs, and please keep the app version and device info in the issue!

App Version: 3.2.2		Device: iPhone 11
		OS: iOS 17.2.1

**Comment by daneden** [comment]
Hey @SohamGovande, thanks for the feedback. This is a known issue and I have already informed the Vercel team. Their recent upgrade for personal accounts → team accounts seems to have also included some changes to this scope selector screen, so hopefully this issue is now fixed.
