### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by johnyfernandes** [daneden/Zeitgeist#106]
Hello! First of all, congrats on this awesome app!

The only problem with it, which is an essential feature, is the notifications, they ain't showing up!

Hope you are able and have time to fix it soon!

**Comment by daneden** [comment]
Hey @johnyfernandes, thanks for your patience waiting for a fix/reply to this issue. I’m closing this issue in favour of #107 as the place to track investigation and updates.

**Comment by johnyfernandes** [comment]
Thank you very much for your reply, and best of luck with this awesome project!
