### ISSUE TITLE
Dont show cancelled deployments as current prod deployment

### ISSUE THREAD

**Issue by motz0815** [daneden/Zeitgeist#108]
If there was a push to master that was cancelled by the build step cancellation, zeitgeist still shows it as the current prod deployment.
![image](https://github.com/daneden/Zeitgeist/assets/49114741/944b2bac-7e0f-41ba-8d4d-1077b57102bf)
App Version: 3.2.2		Device: iPhone16,2
		OS: iOS 17.3.1

**Comment by daneden** [comment]
Thanks for the feedback @motz0815! This issue will be fixed in the next patch version (v3.2.4)
