### ISSUE TITLE
Don't see any way of viewing analytics.

### ISSUE THREAD

**Issue by derad** [daneden/Zeitgeist#109]
> Please give a detailed description of the issue you’re experiencing or the feedback you’d like to provide.
> Feel free to attach any relevant screenshots or logs, and please keep the app version and device info in the issue!

App Version: 3.2.2		Device: iPhone 13 Pro
		OS: iOS 17.4.1

**Comment by daneden** [comment]
Hi @derad! Analytics for Vercel deployments is out of scope for Zeitgeist. The Vercel API does not provide access to analytics data.
