### ISSUE TITLE
Make mobile version?

### ISSUE THREAD

**Issue by agustif** [daneden/zeitgeist#15]
Hey since Now app is not working anymore, this would be nice on iOs for on the go, I could even understand a PWA if app store is not viable.

Whatdyathhink?

**Comment by daneden** [comment]
Ohh that's not a bad idea! I'd be worried that the app is too simple/niche to meet Apple's App Store criteria, but could always make it available via TestFlight.

**Comment by agustif** [comment]
I would check with @rauchg what's their plans on the old official Now app, It's been unusable for me for a long time though... I'd love any alternative.

**Comment by daneden** [comment]
Update: this is tremendously easy in the Xcode 12 updates to SwiftUI so it’ll be coming in v2 (#16). Fingers crossed Apple approves a submission to the App Store for it! Let me know if you have any specific feature requests for a mobile version.

**Comment by daneden** [comment]
Update: the mobile version is now shipped! The v2 branch is still not merged since it’s also going to introduce changes to desktop that are currently work-in-progress, but closing this issue!

https://apps.apple.com/us/app/zeitgeist/id1526052028
