### ISSUE TITLE
iOS crash due to invalid Gitlab commit structure

### ISSUE THREAD

**Issue by wzulfikar** [daneden/zeitgeist#25]
If one of the deployment is from Gitlab, the app will crash because it could not find the deployment url due to invalid structure.

https://github.com/daneden/zeitgeist/blob/3d2a78db50b92b1f43838e0ead7ae387f0348630/Shared/Models/GitCommit.swift#L68-L71

Based on above code (L70-71), if my Gitlab repo is:
- username (project namespace): `wzulfikar`
- repo name (repo key): `Acme App`

The resulting url will be `https://gitlab.com/Acme App/wzulfikar/-/commit/[some commit hash]`. This results to 404 and make the app crash. 

To fix this, the correct commit for Gitlab repo should be `https://gitlab.com/wzulfikar/acme-app/-/commit/[some commit hash]`:

1. Swap the value of `self.repoKey` and `self.namespaceKey`:
    - L70: `self.repoKey` should be `ProjectName`
    - L71: `self.namespaceKey` should be `ProjectNamespace`
2. Use the correct project namespace (from **Acme App** to **acme-app**):
    - Instead of `https://gitlab.com/wzulfikar/Acme App/...`, it should be `https://gitlab.com/wzulfikar/acme-app/...`

To add more context, here's some screenshots:

- This will crash right after login:
![image](https://user-images.githubusercontent.com/7823011/101690879-deb12480-3aa8-11eb-8aa8-401d5f04c6f8.png)

- This will not crash:
![image](https://user-images.githubusercontent.com/7823011/101691560-d0afd380-3aa9-11eb-9e8b-c058d09db653.png)

P.S:
- Based on the error, I think this will affect macOS too as long as one of the deployment is from Gitlab

Hope it helps!

**Comment by daneden** [comment]
Amazing work! Thanks for digging into this, @wzulfikar—I’ll work on a fix right away.

**Comment by daneden** [comment]
Fixed in c196701!

**Comment by daneden** [comment]
The macOS build will be uploaded in a second, and the iOS build will hopefully be available in the next ~48hrs!
