### ISSUE TITLE
Invalid enum in DeploymentState causes the app to crash

### ISSUE THREAD

**Issue by wzulfikar** [daneden/zeitgeist#26]
The app will run smooth until it sees a deployment with state `CANCELED` because the state isn't defined in `DeploymentState` enum.

Exception will occur at line 167 when `deployment["state"]` equals to `CANCELED`:
https://github.com/daneden/zeitgeist/blob/ed317a9ba4023da1fb0b9aa839cf01772921101a/Shared/Networking/VercelFetcher.swift#L163-L171

**Possible fix:** maybe add `case canceled = "CANCELED"` in `DeploymenState` enum:
https://github.com/daneden/zeitgeist/blob/ed317a9ba4023da1fb0b9aa839cf01772921101a/Shared/Models/Deployment.swift#L11-L20

Here's a gif to give more context (17s):
![zeitgeist-invalid-enum mov](https://user-images.githubusercontent.com/7823011/101877720-727a1200-3bc9-11eb-97fb-ebc3eaeecac0.gif)

**Comment by wzulfikar** [comment]
Cool!

**Comment by daneden** [comment]
Good catch, @wzulfikar!
