### ISSUE TITLE
Request: Quicker way to switch teams?

### ISSUE THREAD

**Issue by eivindml** [daneden/zeitgeist#27]
Hi,

first off, love the app! Simple, clean and focused! 🤩

### Feature Request

I would like to see a quicker way to switch between teams. Either a unified view where I can see everything in some way, or that the popover includes the dropdown to switch teams.

### Background

I have a separate team for each of my clients, and I need to switch between these sometimes multiple times a day. And there will be more teams in the future.

<img width="681" alt="Skjermbilde 2020-12-11 kl  09 05 55" src="https://user-images.githubusercontent.com/202450/101878738-602fb200-3b90-11eb-9a92-362483fc2abb.png">

**Comment by daneden** [comment]
Hey @eivindml! This seems reasonable; I can probably put most of the “Settings” into the toolbar on macOS anyway. I’ll plan on addressing this.

**Comment by daneden** [comment]
Hey @eivindml! Just wanted to let you know that this has been addressed in v2.2!
<img width="752" alt="Screenshot 2020-12-23 at 10 15 28" src="https://user-images.githubusercontent.com/439365/102985925-decd0d80-4507-11eb-9d40-44cc1ec3457f.png">

**Comment by eivindml** [comment]
Just wanted to say that this works great 🥳
