### ISSUE TITLE
iOS widget doesn't load

### ISSUE THREAD

**Issue by wzulfikar** [daneden/zeitgeist#28]
I'm at iOS v1.1.3. The app runs smooth after the latest fix for undefined `CANCELED` state. But I noticed that the widgets are stuck in empty view and when I try to edit the widget, it says "Unable to Load". Tried in iPad Mini 5, iPhone SE, and iPhone SE Simulator.

Lmk if there's anything I can do to help debug the widget.

![image](https://user-images.githubusercontent.com/7823011/102006799-e39efe00-3d5e-11eb-8539-88a77ead4485.png)

![image](https://user-images.githubusercontent.com/7823011/102006833-07624400-3d5f-11eb-821a-90740a9518ac.png)

**Comment by wzulfikar** [comment]
Not sure if this is related, but the widget will crash if it sees a team with no deployments (index out of range). I realize that I have one team where I didn't deploy anything yet and thus, I encounter this error.

![image](https://user-images.githubusercontent.com/7823011/102007639-c9b4e980-3d65-11eb-9340-02561ba4c50c.png)

And when I try to change the `entries != nil` to `!entries!.isEmpty` (left image, line 63), it eventually goes to exception (right image).

![Screenshot 2020-12-13 at 11 07 55](https://user-images.githubusercontent.com/7823011/102007681-1c8ea100-3d66-11eb-81c0-d6ec85ff6af7.jpg)

Hope it helps!

**Comment by daneden** [comment]
Hopefully this is fixed in v1.2 of the iOS app/v2.1 of the macOS app! Submitted for App Store review.
