### ISSUE TITLE
iOS stuck at loading when deployment `meta` is empty

### ISSUE THREAD

**Issue by wzulfikar** [daneden/zeitgeist#29]
I just installed the v1.2 for iOS to see if it fixes #28. However, the widget still doesn't load and the UI now will stuck at loading (regression?). 

Upon checking, it seems that the decoder doesn't handle empty `meta` gracefully and the exception wasn't handled too (UI wise). Thus, it stuck at loading state (instead of, eg. showing error message).

Here's a screenshot for context:

1. Exception from decoder
2. Device stuck in loading state
3. Possible cause of decoder exception: `meta` contains empty object instead of data about commit

![image](https://user-images.githubusercontent.com/7823011/102566887-5cb1a300-411b-11eb-940c-948c20178814.png)

P.S:
- in my deployments, those with empty `meta` are projects that I deploy manually (using vercel cli) and weren't connected with git yet (hence the meta is empty).

**Comment by wzulfikar** [comment]
The error only happens in certain teams. I tried to check Vercel API docs to see if I can find when the API returns empty object for `meta`. No luck tho. 

FWIW, I sometimes manually alias my deployment to promote from staging to live. Maybe those manual aliases are the one with empty `meta`.

**Comment by daneden** [comment]
Good catch. I don’t think I realised that a failed decoding for a single key would result in failure to decode the entire response; this should be fixed in 24e5b1d

**Comment by wzulfikar** [comment]
Putting this here for future reference.

I've checked the fix (v1.2.1 of iOS) and it works. Now the screen won't get stuck if it sees manual deployment. Problem fixed ✔️

In addition, I can also see if a push is manual deployment by checking the message (**Manual Deployment**). Thanks for this!

![Screenshot 2020-12-22 at 0 34 08](https://user-images.githubusercontent.com/7823011/102828635-1fe9f280-4420-11eb-82d9-9376531f4335.jpg)
