### ISSUE TITLE
Notification support (macOS) 🚨

### ISSUE THREAD

**Issue by eivindml** [daneden/Zeitgeist#31]
Great app! Would love to see notification support. Just a ping when the latest status changes. Maybe also copy deployment url to clipboard.

I can sometimes do many deployments during a day, and it takes quite some time to build and deploy. So would be nice to just push my code to Github (which automatically deploys to Vercel), and then get a notification (macOS) when it was deployed (or an error occurred). 

This way I can push changes, continue to work, then check out the deployment url when I receive a notification. Right now I have to go to Vercel and check that page multiple times before it's deployed.

**Comment by daneden** [comment]
Hey @eivindml! I just wanted to let you know that I’ve begun work on push notifications for iOS and will soon add them to the macOS app too. I’m planning on adding this as a subscription-tier feature to help cover the ongoing running costs this feature will incur.

**Comment by zomars** [comment]
This would be so helpful! Just purchased the iOS version 🙏🏽

**Comment by zomars** [comment]
Did the macOS app got discontinued?
