### ISSUE TITLE
Title background is missing

### ISSUE THREAD

**Issue by mnlfischer** [daneden/zeitgeist#37]
When starting Zeitgeist, the background for the deployments title is missing. After switching screen e.g. clicking < Zeitgeist and going back to the deployments page, the background has correct background.

iOS: 14.4

https://user-images.githubusercontent.com/3883653/112138674-1a907580-8bd2-11eb-847c-67af4e8fe199.mov

**Comment by daneden** [comment]
Hey @mnlfischer! I've encountered this bug myself and unfortunately think it's a SwiftUI bug. I'll see what I can do to address it but at the very least would anticipate the next version of SwiftUI (which ought to be released later this year) will address it.

**Comment by mnlfischer** [comment]
Thanks for the feedback. Hope SwiftUI gets better with the new release :)
