### ISSUE TITLE
Done button on filter page is not working

### ISSUE THREAD

**Issue by mnlfischer** [daneden/zeitgeist#38]
The done button on filters page does nothing, event when selecting a filter.

iOS: 14.4

https://user-images.githubusercontent.com/3883653/112139147-b7531300-8bd2-11eb-86ae-dfeeb6d8ef38.MP4

**Comment by daneden** [comment]
Hey @mnlfischer, this is a known issue related to SwiftUI. You should be able to drag the filter sheet down to dismiss it after adjusting filters. In v1.6 this button will be removed in favour of drag-down-to-dismiss.

**Comment by mnlfischer** [comment]
@daneden thanks for your feedback. Hope to see a fix from Apple soon :)
