### ISSUE TITLE
Feature request: QOL: Make Production text gold 

### ISSUE THREAD

**Issue by Milo123459** [daneden/zeitgeist#41]
Simply make the text where it says Production with the lightning bolt next to it gold.

**Comment by daneden** [comment]
Hey @Milo123459! Thanks for the suggestion! I’ve explored this before and found it was quite hard to read. In the upcoming v2 release, however, I’m planning on making the icon an orange colour to help make it a bit easier to spot.

**Comment by Milo123459** [comment]
Great! Can't wait.
