### ISSUE TITLE
[Error opening on Mac] Cannot check for malicious software

### ISSUE THREAD

**Issue by philkeys** [daneden/zeitgeist#5]
Hey, I downloaded and attempted to open, however I received this warning. 

<img width="508" alt="warning" src="https://user-images.githubusercontent.com/1406596/76750685-9877a080-6776-11ea-918b-b85f8c093499.png">

**Comment by philkeys** [comment]
Whoops, just needed to go into my system preferences.

**Comment by philkeys** [comment]
Closing this issue.

**Comment by daneden** [comment]
Hey @philkeys! Yep, this is a known issue. Luckily there’s a workaround, as you discovered, but I’m currently chatting with Apple support with an agreements/finance problem that’s preventing me from codesigning my apps right now 🙄 hopefully will be as simple as just double-clicking to open before too long!

**Comment by daneden** [comment]
Hey @philkeys! This should be resolved as of version 1 and up. All releases are now notarized by Apple before uploading to GitHub.
