### ISSUE TITLE
App-submitted issue from João

### ISSUE THREAD

**Issue by daneden** [daneden/Zeitgeist#59]
> Hello! Everything is working fine, but the account row in the primary screen says: “An unknown error occured:
decodingError”. Thank you!

@joao-vasconcelos

**Comment by joao-vasconcelos** [comment]
Hey! Just a few seconds later I noticed an update available, and now instead of the error I get ths: ![image](https://user-images.githubusercontent.com/10943992/152784099-84afec52-e87f-4661-818d-fe0b99100ed2.png)

**Comment by daneden** [comment]
Hey @joao-vasconcelos! Thanks for letting me know about this issue. Would you mind sharing the name and email address associated with the account? Feel free to email me at dan.eden@me.com with this information if you'd rather not leave it in a public comment.

**Comment by joao-vasconcelos** [comment]
Hey Dan, the name is "João de Vasconcelos" and the email is "johnyvasconcelos@icloud.com"

Thanks for looking into it!

**Comment by daneden** [comment]
One more question @joao-vasconcelos; do you have a profile image set for your Vercel account?

**Comment by joao-vasconcelos** [comment]
I logged in with GitHub and it was copied/imported.
