### ISSUE TITLE
Seeing “x” icon instead of Team profile photo

### ISSUE THREAD

**Issue by perryraskin** [daneden/Zeitgeist#68]
Would love to see my Team profile photo instead of the “X” icon. My personal profile photo shows up, but the one for my Team does not. Thanks!

**Comment by daneden** [comment]
Hey Perry! This definitely sounds like a decoding bug: either the avatar image is in an unexpected format, or the team data is in an unexpected format. Would you mind playing around with the Vercel API and letting me know the response of the `/v2/teams/{teamId}` endpoint? 

https://vercel.com/docs/rest-api#teams

**Comment by perryraskin** [comment]
Hey thanks for your quick response! I'm not sure I want to post the response here, but I do see an `avatar` value which appears to be some string with random characters. What should I be looking for?

**Comment by daneden** [comment]
@perryraskin so far so good, that sounds like what I'd expect in the response but it may be that the image format is unusual (e.g. an SVG, WebP, or some other relatively uncommon format). Could you share the "avatar" value here?

**Comment by perryraskin** [comment]
@daneden sure - 74cc7ef80c76c9e11b470801b9355c6484f5ba71

**Comment by daneden** [comment]
@perryraskin thanksI I think this should be fixed in 8dfabe55f1229a8d86fa6099a1d8ee275fb95c09, app version 2.2.2 (which I'll submit this week). It used to be that you needed to pass the team ID rather than avatar ID for team avatars, but I guess that's no longer the case!
