### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by alex289** [daneden/Zeitgeist#79]
Even though I have ever setting on notifications activated I don't get any

**Comment by daneden** [comment]
Hey @alex289! Would you mind providing some more details about your notification settings? For example, a screenshot of the notifications configuration for one of the projects you'd like to receive notifications for?

**Comment by alex289** [comment]
![image](https://user-images.githubusercontent.com/38790209/191259485-d4b7fbf1-8a72-4075-8432-0983e32766d7.png)
![image](https://user-images.githubusercontent.com/38790209/191259500-b615e471-76a6-4e6d-8949-5dfc8a33b980.png)
![image](https://user-images.githubusercontent.com/38790209/191259512-10cef628-f6a0-4039-a7f5-b051c4094b57.png)

**Comment by daneden** [comment]
Thanks @alex289! Could you try [quitting and reopening](https://support.apple.com/en-gb/guide/iphone/iph83bfec492/ios) Zeitgeist and letting me know if this issue still persists? When the app first opens, the device tries to register with the remote notification server. Sometimes when enabling notifications, this registration may fail. Restarting the app may lead to successful registration.

**Comment by alex289** [comment]
Thanks for your work. It's working now :)

**Comment by daneden** [comment]
Glad to hear it! I’ll continue to investigate how this registration happens when turning on notifications anywhere in the app to make it more reliable.
