### ISSUE TITLE
Not getting notifications - iOS - iPhone 13 Pro

### ISSUE THREAD

**Issue by iHildy** [daneden/Zeitgeist#82]
Hey Daniel, this is probably my fault but I can't figure out how. I have notification grouping set to "Deployment" in the iOS app yet I don't get notifications. The "Reset Notification Settings" is grayed out and notifications settings don't show up in the Settings app > Zeitgeist page. Any ideas?

**Comment by ZlatislavZ** [comment]
I got the same issue

**Comment by atridadl** [comment]
Same issue here on a 14 pro.

**Comment by daneden** [comment]
Hey folks, thanks for your patience waiting for a fix/reply to this issue. I’m closing this issue in favour of #107 as the place to track investigation and updates.
