### ISSUE TITLE
cant see projects in organization

### ISSUE THREAD

**Issue by steinarbragi** [daneden/Zeitgeist#85]
I've connected zeitgeist to both my personal account and my organization. I can only see projects from my personal account, the organization shows up empty. However, ios widgets work and show deployments from my organization

![image](https://github.com/daneden/Zeitgeist/assets/3410824/afa4f0b8-df7f-4c8d-abc5-79e06cd22360)> 

![image](https://github.com/daneden/Zeitgeist/assets/3410824/0ce2d83d-e357-45f8-af27-786a371c8e6b)

Please give a detailed description of the issue you’re experiencing or the feedback you’d like to provide.
> Feel free to attach any relevant screenshots or logs, and please keep the app version and device info in the issue!

App Version: 3.1		Device: iPhone 13 mini
		OS: iOS 16.5.1

**Comment by sebszocinski** [comment]
Same here.  My guess is the app doesn't support private organisations?

**Comment by daneden** [comment]
Version 3.2.1 of Zeitgeist, now available in the App Store, fixes the bug that prevented projects from being loaded correctly. Thanks for your patience!

**Comment by daneden** [comment]
Hey @sebszocinski, which version of the app do you have installed? v3.2.2 is the latest in the App Store: v3.2.1 didn't fully fix this issue for some users but v3.2.2 should (hopefully) work for you!

**Comment by sebszocinski** [comment]
I just got the update then (3.2.2) and that's fixed it! thanks
