### ISSUE TITLE
No Notifications on iPhone 14 Pro

### ISSUE THREAD

**Issue by ZlatislavZ** [daneden/Zeitgeist#87]
> I have an iPhone 14 Pro and I don't get any notifications from the app. I have "Group notifications by" set to "Deployment". When I click "Reset Notification Settings" it gets greyed out and still no notifications.

App Version: 3.1		Device: iPhone15,2
		OS: iOS 16.5.1

**Comment by daneden** [comment]
Hey @ZlatislavZ, thanks for your patience waiting for a fix/reply to this issue. I’m closing this issue in favour of #107 as the place to track investigation and updates.
