### ISSUE TITLE
Can't see projects

### ISSUE THREAD

**Issue by CarlAmbroselli** [daneden/Zeitgeist#90]
Hi!

I've purchased the app and linked my account. Small feedback during signup - you can't select the scope since the keyboard overlays:

![IMG_A24854D87412-1](https://github.com/daneden/Zeitgeist/assets/783831/0285f1e8-b7ea-4331-ac18-c700b6eae261)

This can be worked around by using landscape mode.

When I then select my Personal account, it authenticates, but shows "No Projects To Show". 

Any idea what's wrong here?

**Comment by Jadonus** [comment]
I am having same issue. Worked for a while, now I can’t see projects.

**Comment by evan-thurston** [comment]
Is there no fix for this? Pretty frustrating for a paid app

**Comment by bdbergeron** [comment]
Rotating your device to landscape while this screen is shown is the only bypass right now. Unfortunately this is more of an issue with how Vercel's website shows third-party integration authorization and the use of `ASWebAuthenticationSession`, which handles the OAuth handshake in this app. AFAICT there's no easy way to hide the keyboard when this screen is presented.

**Comment by daneden** [comment]
Version 3.2.1 of Zeitgeist, now available in the App Store, fixes the bug that prevented projects from being loaded correctly. Thanks for your patience!
