### ISSUE TITLE
Cannot see any project!

### ISSUE THREAD

**Issue by weico-d** [daneden/Zeitgeist#94]
> Please give a detailed description of the issue you’re experiencing or the feedback you’d like to provide.
> Feel free to attach any relevant screenshots or logs, and please keep the app version and device info in the issue!

App Version: 3.1		Device: iPhone 12
		OS: iOS 17.2

**Comment by daneden** [comment]
Version 3.2.1 of Zeitgeist, now available in the App Store, fixes the bug that prevented projects from being loaded correctly. Thanks for your patience!
