### ISSUE TITLE
My projects aren't showing up any more. Even after removing my account and adding it again. What happened?

### ISSUE THREAD

**Issue by steveDvlpr** [daneden/Zeitgeist#96]
> Please give a detailed description of the issue you’re experiencing or the feedback you’d like to provide.
> Feel free to attach any relevant screenshots or logs, and please keep the app version and device info in the issue!

App Version: 3.1		Device: iPhone15,2
		OS: iOS 17.1.1

**Comment by weico-d** [comment]
![image](https://github.com/daneden/Zeitgeist/assets/108644167/53fa6402-f9d3-4933-99c1-b45ae40f36bc)
same issues，but small widgets working。

**Comment by bdbergeron** [comment]
@steveDvlpr what are your project's [Deployment Protection](https://vercel.com/docs/security/deployment-protection#understanding-deployment-protection-by-environment) settings?

**Comment by Belco90** [comment]
Same here. I have _Standard Protection_ for deployments.

**Comment by bdbergeron** [comment]
@Belco90 #97 should fix things for you once it gets merged in and a new version pushed to the App Store.

**Comment by Belco90** [comment]
Great, thanks! Looking forward to it.

**Comment by daneden** [comment]
Version 3.2.1 of Zeitgeist, now available in the App Store, fixes the bug that prevented projects from being loaded correctly. Thanks for your patience!
